### ISSUE TITLE
nowpayments 1.2.1 error import

### ISSUE THREAD

**Issue by scwall** [Ventura94/NOWPayments-Python-API#9]
**Describe the bug**
Import is broken  for version 1.2.1 in python 

**To Reproduce**
Install nowpayments 1.2.1 on python 3.8
from nowpayments import NOWPayments

**Expected behavior**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nowpayments

**Desktop (please complete the following information):**
 - OS: Ubuntu /Windows

**Additional context**

I have no problem if I install version 1.1.1 of the package I can import it in my terminal, 
Version 1.2.1 cannot be imported in the console (see above)
Thank's

**Comment by Ventura94** [comment]
Resolved
